.\" Copyright (c) 1987-2008 - Sun Microsystems, Inc.
.TH VALUATE 1 "1 July 2026"
.SH NAME
valuate \- a desktop calculator
.SH SYNOPSIS
.B valuate
[
.I OPTION
] ...
.SH DESCRIPTION
.B valuate
is a GTK3/XApp-based desktop calculator.
.SH OPTIONS
.TP
.B \-e, \-\-equation
Start valuate and display the equation following this option.
.TP
.B \-s, \-\-solve
Solve the equation provided following this option.
.TP
.B \-v, \-\-version
Output version information and exit.
.TP
.B \-h, \-?, \-\-help
Prints the command line options.
.SH SEE ALSO
.PD 0
.TP 18
.B valuatecmd
.sp
.LP
